[project]
name = "box"
version = "0.1.2"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
box = "box.cli:main"
pub_version = "box_tools.flutter.pub_version:main"
pub_upgrade = "box_tools.flutter.pub_upgrade:main"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ["src/box", "src/box_tools"]