[project]
name = "box"
version = "0.1.42"
requires-python = ">=3.9"
dependencies = ["PyYAML>=6.0", "openai>=1.0.0", "openai", "PyYAML", "tiktoken"]

[project.scripts]
box = "box.box:main"
pub_publish = "box_tools.flutter.pub_publish:main"
pub_upgrade = "box_tools.flutter.pub_upgrade:main"
pub_version = "box_tools.flutter.pub_version:main"
riverpod_gen = "box_tools.flutter.riverpod_gen:main"
slang_i18n = "box_tools.translate.slang_i18n:main"
strings_i18n = "box_tools.translate.strings_i18n:main"
translate = "box_tools.translate.ai_translate:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ["src/box", "src/box_tools"]

